# Generated by Django 3.1.2 on 2020-10-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('customer_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_line', models.CharField(max_length=50)),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment', models.FloatField()),
                ('cogs', models.FloatField()),
                ('profit', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
